version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/banchango
hooks:
        BeforeInstall:
                - location: scripts/delete-before-artifacts.sh
        AfterInstall:
                - location: scripts/change-script-permissions.sh
        ApplicationStart:
                - location: scripts/run-application.sh
                  runas: ubuntu
